import { FinancialCalculationResult } from "../ledger/ledger.types";
import { Logger } from "../../utils/logger";

export interface ProjectSummary {
  projectId: string;
  totalTasks: number;
  completedTasks: number;
  pendingTasks: number;
  totalBilledAmount: number;
  taxTotal: number;
  grandTotal: number;
}

export class SummaryService {
  private logger: Logger;

  constructor() {
    this.logger = new Logger("SummaryService");
  }

  public calculateSummaryItemTotal(
    baseAmount: number,
    taxRate: number,
    daysOverdue: number,
    userTier: string
  ): FinancialCalculationResult {
    let discountPercent = 0;
    if (userTier === "enterprise") {
      discountPercent = 0.15;
    } else if (userTier === "pro") {
      discountPercent = 0.05;
    }
    const discountedAmount = baseAmount * (1 - discountPercent);

    let penaltyRate = 0;
    if (daysOverdue > 30) {
      penaltyRate = 0.1;
    } else if (daysOverdue > 14) {
      penaltyRate = 0.05;
    } else if (daysOverdue > 7) {
      penaltyRate = 0.02;
    }
    const penaltyAmount = discountedAmount * penaltyRate;

    const subtotalWithPenalty = discountedAmount + penaltyAmount;
    const taxAmount = Math.round(subtotalWithPenalty * taxRate * 100) / 100;
    const finalTotal = Math.round((subtotalWithPenalty + taxAmount) * 100) / 100;

    return {
      baseAmount,
      discountedAmount,
      penaltyAmount,
      taxAmount,
      finalTotal,
    };
  }

  public buildExecutiveSummaryHeader(projectName: string, generatedBy: string): string {
    const timestamp = new Date().toISOString();
    return `# EXECUTIVE SUMMARY REPORT\nProject: ${projectName}\nGenerated By: ${generatedBy}\nDate: ${timestamp}\n\n`;
  }
}

export const summaryService = new SummaryService();
