import fs from 'node:fs';
import path from 'node:path';
import type Anthropic from '@anthropic-ai/sdk';
import { createClaudeClient } from '../../services/claude-client.js';
import type {
  CodeSmellAnalysisResult,
  CodeSmellObservation,
  CodeTechDebtScore,
  CycleDetectionResult,
} from './ast/types.js';

/**
 * Structured refactoring explanation generated by Claude for a specific code observation.
 */
export interface CodeObservationExplanation {
  observationId: string;
  explanation: string;
  likelyImpact: string;
  recommendation: string;
  refactorExample?: string;
  confidence?: 'high' | 'medium' | 'low';
}

/**
 * Top-level structured response payload returned by the Code Analyzer Claude prompt.
 */
export interface CodeOptimizationResponse {
  summaryOverview?: string;
  explanations: CodeObservationExplanation[];
}

/**
 * Input payload supplied to the prompt builder.
 */
export interface CodeOptimizationRequest {
  cyclesResult: CycleDetectionResult;
  smellsResult: CodeSmellAnalysisResult;
  techDebtScore: CodeTechDebtScore;
  /** Optional directory path to read source file snippets defensively */
  rootDir?: string;
}

/**
 * System prompt instructing Claude on deterministic code analysis grounding,
 * refactoring safety, and structured JSON output.
 */
export const CODE_ANALYZER_SYSTEM_PROMPT = `You are a Principal Software Architect and Static Code Analysis Specialist for CodeInsight.
Your task is to analyze deterministic code quality findings, circular dependencies, code smells, and tech-debt metrics, and generate plain-English explanations, refactoring recommendations, and advisory code examples.

STRICT OPERATIONAL CONSTRAINTS:
1. GROUNDING MANDATE: You MUST accept the provided deterministic rule findings, circular dependencies, and tech-debt score as absolute ground truth. Do NOT invent new code smells, modify severities, delete findings, or alter observation IDs.
2. ADVISORY SAFETY: Refactor recommendations are strictly advisory and informational. You MUST NOT execute shell commands, run tests, modify repository files, install dependencies, or claim that a refactor has been executed or verified.
3. ADVISORY REFACTOR EXAMPLES: Any code examples provided MUST be clearly presented as illustrative examples only and MUST NOT alter the application's runtime contracts or external behavior.
4. PROMPT & SECRET SAFETY: Never expose credentials, API keys, database URLs, or secret tokens in prompt content or responses.
5. STRUCTURED JSON OUTPUT: You MUST respond ONLY with a valid JSON object conforming strictly to the requested schema. Do NOT surround your response with conversational markdown text outside the JSON object.`;

/**
 * Reads a bounded source snippet from disk if available, capping lines and characters to prevent prompt bloat.
 */
function getBoundedSourceSnippet(
  rootDir: string | undefined,
  relPath: string,
  startLine?: number,
  endLine?: number,
  maxLines = 40,
  maxChars = 1500
): string | null {
  if (!rootDir || !relPath) return null;
  try {
    const absPath = path.resolve(rootDir, relPath);
    // Security check: ensure path stays within rootDir
    if (!absPath.startsWith(path.resolve(rootDir))) return null;
    if (!fs.existsSync(absPath)) return null;

    const fileContent = fs.readFileSync(absPath, 'utf8');
    const lines = fileContent.split(/\r?\n/);

    const start = Math.max(1, startLine || 1);
    const end = Math.min(lines.length, endLine || start + maxLines - 1);

    if (end - start + 1 > maxLines) {
      return null; // Omit oversized snippets to maintain prompt bounds
    }

    const snippetLines = lines.slice(start - 1, end);
    let snippet = snippetLines.join('\n');

    if (snippet.length > maxChars) {
      snippet = snippet.substring(0, maxChars) + '\n... [truncated]';
    }

    // Strip sensitive patterns if present
    snippet = snippet.replace(
      /(?:key|secret|token|password|auth|bearer|api_key)\s*[:=]\s*['"][^'"]+['"]/gi,
      '[REDACTED_SECRET]'
    );

    return snippet;
  } catch {
    return null;
  }
}

/**
 * Sanitizes input strings against accidental secret leakage.
 */
function sanitizeText(text: string): string {
  if (!text) return '';
  return text
    .replace(/sk-ant-[a-zA-Z0-9_-]+/g, '[REDACTED_ANTHROPIC_KEY]')
    .replace(/sk-[a-zA-Z0-9_-]+/g, '[REDACTED_API_KEY]')
    .replace(/postgres:\/\/[^\s]+/g, '[REDACTED_DB_URL]')
    .replace(/postgresql:\/\/[^\s]+/g, '[REDACTED_DB_URL]')
    .replace(/clerk_[a-zA-Z0-9_-]+/g, '[REDACTED_CLERK_KEY]');
}

/**
 * Build system and user prompt strings for Claude given the deterministic analysis results.
 */
export function buildCodeAnalysisPrompt(input: CodeOptimizationRequest): {
  systemPrompt: string;
  userPrompt: string;
} {
  const score = input.techDebtScore;
  const cycles = input.cyclesResult?.cycles || [];
  const observations = input.smellsResult?.observations || [];

  const scoreSummary = `### TECH-DEBT SCORE BREAKDOWN:
- Score: ${score.score} / 100 (${score.band.toUpperCase()})
- Empty Repository: ${score.isEmptyRepository ? 'Yes' : 'No'}
- Production Files: ${score.counts.productionFiles} | Test Files: ${score.counts.testFiles} (Test Ratio: ${(score.testFileRatio * 100).toFixed(1)}%)
- Penalties:
  - Circular Dependencies: ${score.penalties.circularDependencies} / 30 pts (${score.counts.circularDependencies} cycles)
  - Long Functions: ${score.penalties.longFunctions} / 20 pts (${score.counts.longFunctions} total, ${score.counts.highSeverityLongFunctions} high severity)
  - Duplicate Logic: ${score.penalties.duplicateLogic} / 20 pts (${score.counts.duplicateLogic} duplicates)
  - Unused Exports: ${score.penalties.potentiallyUnusedExports} / 10 pts (${score.counts.potentiallyUnusedExports} unused)
  - Comment Debt: ${score.penalties.commentDebt} / 10 pts (TODO: ${score.counts.todoMarkers}, FIXME: ${score.counts.fixmeMarkers}, HACK: ${score.counts.hackMarkers}, XXX: ${score.counts.xxxMarkers})
  - Test Ratio Penalty: ${score.penalties.testFileRatio} / 5 pts
  - Total Penalty: ${score.penalties.total} pts`;

  const cyclesSummary =
    cycles.length > 0
      ? cycles
          .slice(0, 10) // Bounded cycle context
          .map(
            (c, idx) => `Cycle #${idx + 1}:
- Cycle ID: ${c.id}
- Nodes (${c.length}): ${c.nodes.join(' -> ')}`
          )
          .join('\n\n')
      : 'No circular dependencies detected.';

  const observationsSummary =
    observations.length > 0
      ? observations
          .slice(0, 20) // Bounded observation context
          .map((o, idx) => {
            const snippet = getBoundedSourceSnippet(input.rootDir, o.file, o.startLine, o.endLine);
            return `Observation #${idx + 1}:
- ID: ${o.id}
- Rule ID: ${o.ruleId}
- Severity: ${o.severity}
- File: ${o.file} ${o.startLine ? `(Lines ${o.startLine}-${o.endLine || o.startLine})` : ''}
- Message: ${o.message}
${snippet ? `- Source Snippet:\n\`\`\`ts\n${snippet}\n\`\`\`` : ''}`;
          })
          .join('\n\n')
      : 'No code smells detected.';

  const userPrompt = sanitizeText(`${scoreSummary}

### CIRCULAR DEPENDENCIES:
${cyclesSummary}

### CODE SMELL OBSERVATIONS:
${observationsSummary}

### REQUIRED OUTPUT FORMAT:
Return a single JSON object with the following structure:
{
  "summaryOverview": "Executive narrative explaining where the primary tech debt originates based on the score and findings.",
  "explanations": [
    {
      "observationId": "<matching deterministic observation ID>",
      "explanation": "Clear, plain-English explanation of why this observation creates architectural debt or maintenance risk.",
      "likelyImpact": "Description of potential downstream risks (e.g. refactoring difficulty, tight coupling, performance).",
      "recommendation": "Actionable refactoring advice to eliminate the smell or break the dependency cycle.",
      "refactorExample": "Illustrative code snippet demonstrating a safe refactored approach (if applicable, otherwise omit)",
      "confidence": "high"
    }
  ]
}`);

  return {
    systemPrompt: CODE_ANALYZER_SYSTEM_PROMPT,
    userPrompt,
  };
}

/**
 * Defensively parses raw text returned by Claude, ensuring valid JSON schema and filtering unknown observation IDs.
 */
export function parseClaudeCodeResponse(
  rawText: string,
  validObservationIds: Set<string>
): CodeOptimizationResponse {
  if (!rawText || typeof rawText !== 'string') {
    return { explanations: [] };
  }

  let cleaned = rawText.trim();
  // Strip markdown code fences if present
  if (cleaned.startsWith('```')) {
    cleaned = cleaned
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/i, '')
      .trim();
  }

  try {
    const parsed = JSON.parse(cleaned);
    if (!parsed || typeof parsed !== 'object') {
      return { explanations: [] };
    }

    const summaryOverview =
      typeof parsed.summaryOverview === 'string' ? parsed.summaryOverview : undefined;
    const rawExplanations = Array.isArray(parsed.explanations) ? parsed.explanations : [];

    const validExplanations: CodeObservationExplanation[] = [];

    for (const item of rawExplanations) {
      if (!item || typeof item !== 'object') continue;

      const observationId = String(item.observationId || '');
      const explanation = String(item.explanation || '');
      const likelyImpact = String(item.likelyImpact || '');
      const recommendation = String(item.recommendation || '');

      // Reject items missing required fields
      if (!observationId || !explanation || !likelyImpact || !recommendation) {
        continue;
      }

      // Grounding safeguard: reject explanations referencing unknown observation IDs
      if (!validObservationIds.has(observationId)) {
        continue;
      }

      const confidence = ['high', 'medium', 'low'].includes(item.confidence)
        ? item.confidence
        : 'high';
      const refactorExample =
        typeof item.refactorExample === 'string' && item.refactorExample.trim()
          ? item.refactorExample.trim()
          : undefined;

      validExplanations.push({
        observationId,
        explanation,
        likelyImpact,
        recommendation,
        refactorExample,
        confidence,
      });
    }

    return {
      summaryOverview,
      explanations: validExplanations,
    };
  } catch {
    return { explanations: [] };
  }
}

/**
 * Enhances deterministic CodeSmellObservation items with Claude explanations without mutating deterministic properties.
 */
export function enhanceCodeObservationsWithClaude(
  smellsResult: CodeSmellAnalysisResult,
  claudeResponse: CodeOptimizationResponse
): CodeSmellAnalysisResult {
  const explanationMap = new Map<string, CodeObservationExplanation>();
  for (const exp of claudeResponse.explanations || []) {
    explanationMap.set(exp.observationId, exp);
  }

  const enhancedObservations: CodeSmellObservation[] = (smellsResult.observations || []).map(
    (obs) => {
      const exp = explanationMap.get(obs.id);
      if (!exp) return obs;

      return {
        ...obs,
        metadata: {
          ...obs.metadata,
          aiExplanation: {
            explanation: exp.explanation,
            likelyImpact: exp.likelyImpact,
            recommendation: exp.recommendation,
            refactorExample: exp.refactorExample,
            confidence: exp.confidence || 'high',
          },
        },
      };
    }
  );

  return {
    ...smellsResult,
    observations: enhancedObservations,
  };
}

/**
 * Orchestrates Claude API execution using shared Anthropic client, providing deterministic offline fallback.
 */
export async function generateCodeOptimizationsWithClaude(
  input: CodeOptimizationRequest,
  client?: Anthropic
): Promise<CodeOptimizationResponse> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  const isUnconfigured = !apiKey || apiKey === 'unconfigured_key';

  const validObservationIds = new Set<string>([
    ...(input.smellsResult?.observations || []).map((o) => o.id),
    ...(input.cyclesResult?.cycles || []).map((c) => c.id),
  ]);

  // Deterministic offline fallback when API key is missing
  if (isUnconfigured) {
    return {
      summaryOverview:
        'AI explanation is unavailable (ANTHROPIC_API_KEY unconfigured). Deterministic findings remain 100% active.',
      explanations: [],
    };
  }

  try {
    const anthropic = client || createClaudeClient(apiKey);
    const { systemPrompt, userPrompt } = buildCodeAnalysisPrompt(input);

    const response = await anthropic.messages.create({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 2048,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    });

    const textBlock = response.content.find((c) => c.type === 'text');
    const rawText = textBlock ? textBlock.text : '';

    const parsed = parseClaudeCodeResponse(rawText, validObservationIds);

    // If parsing produced zero valid explanations, return graceful fallback summary
    if (!parsed.summaryOverview && parsed.explanations.length === 0) {
      return {
        summaryOverview: 'AI explanation processing completed with empty response.',
        explanations: [],
      };
    }

    return parsed;
  } catch {
    // API call failure fallback: return deterministic response without throwing uncaught errors
    return {
      summaryOverview:
        'AI explanation service encountered an error. Deterministic findings remain unaffected.',
      explanations: [],
    };
  }
}
